<?php /*
   @copyright  Copyright (c) 2009-2010 Keleo (http://www.keleo.de)
   @license    http://www.bigace.de/license.html     GNU Public License
   @version    $Id$

*/

    $MENU        = $this->MENU;
    $LANGUAGE    = $this->LANGUAGE;
    $passID      = (isset($MENU) ? $MENU->getID() : null);
    $imageURL    = Bigace_Editor_Dialogs::getImageDialogSettings($passID);
    $linkURL     = Bigace_Editor_Dialogs::getLinkDialogSettings($passID);


if(isset($this->SHOW_TRANSLATOR) && $this->SHOW_TRANSLATOR != '')
{
    ?>
    <style type="text/css">
    </style>
    <?php
}

?>
<script type="text/javascript">
<!--
    var isDirty = false;

    function resetIsDirtyEditor() {
        isDirty = false;
    }
    function setIsDirtyEditor() {
        isDirty = true;
        return true;
    }
    function isDirtyEditor() {
        return isDirty;
    }
// -->
</script>
