<?php /* 
   @copyright  Copyright (c) 2009-2010 Keleo (http://www.keleo.de)
   @license    http://www.bigace.de/license.html     GNU Public License
   @version    $Id$
   
*/
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php if(isset($this->STYLESHEET) && $this->STYLESHEET !== null) { ?>
    <link rel="stylesheet" href="<?php echo $this->STYLESHEET; ?>" type="text/css">
<?php } ?>
    <title><?php echo $this->t("title"); ?></title>
</head>
<body class="translateBody">
	<div id="translateContent">
		<?php echo $this->content; ?>
	</div>
</body>
</html>
