<?php
/* @license http://opensource.org/licenses/gpl-license.php GNU Public License
   @author Kevin Papst
   @copyright Copyright (C) Kevin Papst
   @version $Id$ */

if(isset($this->ERROR) && count($this->ERROR) > 0)
    foreach($this->ERROR as $err)
        echo $this->message($err, 'error');

if(isset($this->INFO) && count($this->INFO) > 0)
    foreach($this->INFO as $inf)
        echo $this->message($inf, 'info');
?>

<form action="<?php echo $this->FORM_ACTION; ?>" method="post">

<input type="hidden" name="" value="" />
<input type="hidden" name="" value="" />

<h2><?php echo $this->t('config_domain'); ?></h2>

<table class="" width="100%" cellspacing="0">
 <col width="250" />
 <col width="100" />
 <col />

 <tbody>
    <tr>
        <td><?php echo $this->t('new_domain'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('new_domain_help'); ?>"></td>
        <td><?php echo $this->formText('data[newdomain]', $this->NEW_DOMAIN, array('id' => 'newdomain')); ?></td>
    </tr>
 </tbody>
</table>

<h2><?php echo $this->t('config_consumer'); ?></h2>

<table class="" width="100%" cellspacing="0">
 <col width="250" />
 <col width="100" />
 <col />
 <tbody>
    <tr>
        <td><?php echo $this->t('sitename'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('sitename_help'); ?>"></td>
        <td><?php echo $this->formText('data[sitename]', $this->SITENAME, array('id' => 'sitename')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->t('default_editor'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('default_editor_help'); ?>"></td>
        <td><?php echo $this->EDITOR_CHOOSER; ?></td>
    </tr>
    <tr>
        <td><?php echo $this->t('default_language'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('default_language_help'); ?>"></td>
        <td><?php echo $this->DEFAULT_LANGUAGE; ?></td>
    </tr>
 </tbody>
</table>

<h2><?php echo $this->t('config_admin'); ?></h2>

<table class="" width="100%" cellspacing="0">
 <col width="250" />
 <col width="100" />
 <col />
 <tbody>
    <tr>
        <td><?php echo $this->t('bigace_admin'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('bigace_admin_help'); ?>"></td>
        <td><?php echo $this->formText('data[admin]', $this->ADMIN_NAME, array('id' => 'admin')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->t('webmastermail'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('webmastermail_help'); ?>"></td>
        <td><?php echo $this->formText('data[webmastermail]', $this->SITE_EMAIL, array('id' => 'webmastermail')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->t('bigace_password'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('bigace_password_help'); ?>"></td>
        <td><?php echo $this->formPassword('data[password]', '', array('id' => 'password')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->t('bigace_check'); ?></td>
        <td align="center"><img class="tooltip" src="<?php echo $this->STYLE; ?>info.png" title="<?php echo $this->t('bigace_check_help'); ?>"></td>
        <td><?php echo $this->formPassword('data[check]', '', array('id' => 'check')); ?></td>
    </tr>
 </tbody>
</table>

<?php echo $this->formButton('createInstall', $this->t('create_button'), array('type' => 'submit')); ?>
</form>
