<?php
/**
 * Bigace - a PHP and MySQL based Web CMS.
 *
 * LICENSE
 *
 * This source file is subject to the new GNU General Public License
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://www.bigace.de/license.html
 *
 * Bigace is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * @category   Bigace
 * @copyright  Copyright (c) 2009-2010 Keleo (http://www.keleo.de)
 * @license    http://www.bigace.de/license.html     GNU Public License
 * @version    $Id$
 */

/** @var $base string */
$base = $this->base;
?>

<h1><?php echo installTranslate('menu_step_'.MENU_STEP_SUCCESS); ?></h1>

<?php echo installTranslate('community_install_good'); ?>

<a href="<?php echo $base; ?>" class="buttonLink">&raquo; <?php echo installTranslate('community_install_button'); ?></a>
