<?php /* @license http://opensource.org/licenses/gpl-license.php GNU Public License
   @author Kevin Papst
   @copyright Copyright (C) Kevin Papst
   @version $Id$ */

$this->dojo()->enable()
             ->requireModule('dijit.MenuBar')
             ->requireModule('dijit.MenuBarItem')
             ->requireModule('dijit.MenuItem')
             ->requireModule('dijit.PopupMenuBarItem')
             ->requireModule('dijit.MenuSeparator');

echo $this->partial('partial_header.phtml', array(
    'STYLE'    => $this->STYLE,
    'ITEM'     => $this->ITEM,
    'URL_MOVE' => $this->URL_MOVE,
    'URL_MODE' => $this->URL_MODE
));

echo $this->partial('partial_toolbar.phtml', array(
    'TOOLBAR_ENTRIES' => $this->TOOLBAR_ENTRIES,
    'ITEM'            => $this->ITEM,
    'STYLE'           => $this->STYLE
));

if (isset($this->ERROR)) {
    echo $this->message($this->ERROR, 'error');
}

if (isset($this->INFO)) {
    echo $this->message($this->INFO, 'info');
}

if(!isset($this->noBacklink) || $this->noBacklink !== true) {
    echo $this->backlink($this->BACK_URL);
}

echo $this->partial('partial_properties_start.phtml', array(
    'STYLE'             => $this->STYLE,
    'ITEM'              => $this->ITEM,
    'FORM_ACTION'       => $this->FORM_ACTION,
    'tempLanguage'      => $this->tempLanguage,
    'supportUniqueName' => $this->supportUniqueName,
    'BASE_ITEM_URL'     => $this->BASE_ITEM_URL
));

echo $this->partial('partial_properties_hooks.phtml', array(
    'META_VALUES' => $this->META_VALUES
));

echo $this->partial('partial_properties_end.phtml', array(
    'SUPPORT_UPLOAD' => $this->SUPPORT_UPLOAD,
    'ITEM'           => $this->ITEM,
    'UPLOAD_URL'     => $this->UPLOAD_URL
));

echo $this->partial('partial_metainfo.phtml', array(
    'ITEM'        => $this->ITEM,
    'ITEM_URL'    => $this->ITEM_URL,
    'LAST_USER'   => $this->LAST_USER,
    'CREATE_USER' => $this->CREATE_USER
));

echo $this->partial('partial_footer.phtml', array(
    'BASE_ITEM_URL'   => $this->BASE_ITEM_URL,
    'REMOVE_LANGUAGE' => $this->REMOVE_LANGUAGE
));
