<?php
/**
 * Bigace - a PHP and MySQL based Web CMS.
 *
 * LICENSE
 *
 * This source file is subject to the new GNU General Public License
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://www.bigace.de/license.html
 *
 * Bigace is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * @category   Bigace
 * @copyright  Copyright (c) 2009-2010 Keleo (http://www.keleo.de)
 * @license    http://www.bigace.de/license.html     GNU Public License
 * @version    $Id$
 */

/** @var $step string */
$step = $this->step;

/** @var $base string */
$base = INSTALL_PUBLIC;

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <title><?php echo installTranslate('browser-title'); ?></title>
    <link rel="stylesheet" href="<?php echo $base; ?>/install.css" type="text/css" />
    <script src="<?php echo $base; ?>/install.js" type="text/javascript"></script>
    <script src="<?php echo $base; ?>/overlib_mini.js" type="text/javascript"></script>
    <?php /* Input field tooltip, initialized in header */ ?>
    <link rel="stylesheet" href="<?php echo $base; ?>/form-field-tooltip.css" media="screen" type="text/css">
    <script src="<?php echo $base; ?>/rounded-corners.js" type="text/javascript"></script>
    <script src="<?php echo $base; ?>/form-field-tooltip.js" type="text/javascript"></script>
</head>
<body>
    <div id="overDiv" style="position:absolute;visibility:hidden; z-index:1000;"></div>
    <div class="outer">
        <h1 class="header">
            <?php echo installTranslate('menu_title'); ?>
            <span><?php echo installTranslate('thanks'); ?></span>
        </h1>
        <div class="updateBox">
            <?php if($step > 1 && $step < 5) { ?>
            <p class="navEntry"><?php echo installTranslate('menu_step'); ?> <?php echo $step-1; ?> / 3: <?php echo installTranslate('menu_step_'.($step)); ?></p>
            <?php } ?>
            <div class="contentTD">

                <?php echo $this->layout()->content; ?>

            </div>
        </div>
    </div>

    <script type="text/javascript">
    var tooltipObj = new DHTMLgoodies_formTooltip();
    tooltipObj.imagePath = '<?php echo INSTALL_PUBLIC; ?>/';
    tooltipObj.setTooltipPosition('right');
    tooltipObj.setPageBgColor('#EEEEEE');
    tooltipObj.setTooltipCornerSize(10);
    tooltipObj.initFormFieldTooltip();
    tooltipObj.setTooltipWidth(250) ;
    tooltipObj.setCloseMessage("<?php echo installTranslate('form_tip_close'); ?>");
    tooltipObj.setDisableTooltipMessage("<?php echo installTranslate('form_tip_hide'); ?>");
    </script>

</body>
</html>
